[package]
name = "metronic"
version = "1.0.0"
entrypoint = "template/template.typ"
authors = ["Patrick Rabier <https://tronica.io>"]
license = "JSON"
description = "A clean, colorful, and modern CV template."
repository = "https://github.com/patrixr/metronic-cv"
categories = ["cv"]
keywords = ["CV", "Resume", "Color", "Sidebar"]
exclude = ["*.pdf"]

[template]
path = "preview"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
